# Generated by Django 5.2.4 on 2025-08-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coach_name',
        ),
        migrations.AddField(
            model_name='team',
            name='coach_first_name',
            field=models.CharField(default='Brandon', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='coach_last_name',
            field=models.CharField(default='Altamirano', max_length=50),
            preserve_default=False,
        ),
    ]
