# Generated by Django 4.2.23 on 2025-08-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_teammembership_team_alter_teammembership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('player', 'Player')], max_length=10),
        ),
    ]
