# Generated by Django 4.2.23 on 2025-08-12 22:22

from django.db import migrations
from django.contrib.auth import get_user_model

User = get_user_model()

def create_teams(apps, schema_editor):
    team_model = apps.get_model('teams', 'Team')
    names = ['Aztecs FC', 'Rebels SC', 'Albion SC', 'Atlante FC', 'Nomads SC', 'Chula Vista FC']

    for name in names:
        if not team_model.objects.filter(name__iexact=name).exists():
            team_model.objects.create(
                name=name
            )

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_teammembership_status_alter_teammembership_role'),
    ]

    operations = [
        migrations.RunPython(create_teams)
    ]
