# Generated by Django 5.2.4 on 2025-09-23 06:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_create_dummy_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='email',
            field=models.CharField(default='manabran501@hotmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='first_name',
            field=models.CharField(default='Brandon', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='last_name',
            field=models.CharField(default='Altamirano', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='logo_file_path',
            field=models.CharField(default='path', max_length=200),
            preserve_default=False,
        ),
    ]
