# Generated by Django 5.2.4 on 2025-09-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_playerprofile_email_playerprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='profile_photo',
            field=models.CharField(default='logos/profile_pic.png', max_length=200),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='playerprofile',
            constraint=models.UniqueConstraint(fields=('team', 'email'), name='uniq_player_email_per_team'),
        ),
    ]
