# Generated by Django 5.2.4 on 2025-10-06 05:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_playerprofile_public_id_alter_playerprofile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
