# Generated by Django 5.2.4 on 2025-08-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='6198023753', max_length=15),
            preserve_default=False,
        ),
    ]
