# Generated by Django 4.2.23 on 2025-08-12 22:01

from django.db import migrations
from django.contrib.auth import get_user_model
from django.db.models import Q
from users.constants import GENERIC_PASSWORD, PLAYER_COUNT, COACH_COUNT

User = get_user_model()

def create_users(apps, schema_editor):
    for i in PLAYER_COUNT:
        if not User.objects.filter(
            Q(email__iexact = f"player{i.lower()}@gmail.com") |
            Q(username__iexact = f"player{i.lower()}")
        ).exists():
            user = User.objects.create_user(
                first_name = "Player",
                last_name = i,
                email = f"player{i.lower()}@gmail.com",
                username = f"player{i.lower()}",
                phone = "6195558888"
            )
            user.set_password(GENERIC_PASSWORD)
            user.save()
    
    for i in COACH_COUNT:
        if not User.objects.filter(
            Q(email__iexact = f"coach{i.lower()}@gmail.com") |
            Q(username__iexact = f"coach{i.lower()}")
        ).exists():
            user = User.objects.create_user(
                first_name = "Coach",
                last_name = i,
                email = f"coach{i.lower()}@gmail.com",
                username = f"coach{i.lower()}",
                phone = "6195558888"
            )
            user.set_password(GENERIC_PASSWORD)
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.RunPython(create_users)
    ]