# Generated by Django 5.2.4 on 2025-09-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=10),
            preserve_default=False,
        ),
    ]
