# Generated by Django 5.2.4 on 2025-09-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_league_status'),
        ('teams', '0009_team_is_paid_alter_playerprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamstanding',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='teamstanding',
            constraint=models.UniqueConstraint(fields=('team', 'league'), name='uniq_team_per_league'),
        ),
    ]
