# Generated by Django 5.2.4 on 2025-10-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_teamstanding_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('league', 'Leauge'), ('quarter-final', 'Quarter-final'), ('semi-final', 'Semi-final'), ('final', 'Final')], default='league', max_length=20),
            preserve_default=False,
        ),
    ]
